apiVersion: v1
kind: Pod
metadata:
  name: openshift-cicd-artifact-checker
  namespace: ocp-cicd-deploy
  labels:
    {{- include "openshift-cicd-demo.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "0"
spec:
  containers:
    - name: checker-cicd-artifacts
      image: quay.io/redhatworkshops/ocp-cicd-deploy:latest
      command:
        - /bin/bash
        - -c
        - |
          export HOME=/tmp/checker
          ## Simple, we just check the existance of Argo CD applications (for now)
          echo "Waiting for the Applications to appear"
          echo "======================================"
          until [[ $(oc get applications --all-namespaces -o name | wc -l) -gt 0 ]]; do sleep 5; done; echo "DONE"
          ## Exit 0 since this is a "best effort"
          exit 0
      imagePullPolicy: Always
  restartPolicy: Never
  serviceAccount: ocp-cicd-demo
  serviceAccountName: ocp-cicd-demo
