apiVersion: v1
kind: Pod
metadata:
  name: openshift-cicd-artifact-deleter
  namespace: ocp-cicd-deploy
  labels:
    {{- include "openshift-cicd-demo.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "0"
spec:
  containers:
    - name: deleter-cicd-artifacts
      image: quay.io/redhatworkshops/ocp-cicd-deploy:latest
      command:
        - /bin/bash
        - -c
        - |
          export HOME=/tmp/looper
          ## oAuth is a bitch so we'll turn off automatic syncing
          ## and patch the application/sets before we do anything else
          oc patch applicationsets cicd-demo -n openshift-gitops --type=json -p='[{"op": "replace", "path": "/spec/template/spec/syncPolicy/automated/selfHeal", "value":false}]'
          oc patch application cluster-config -n openshift-gitops --type=merge --patch '{"spec":{"syncPolicy":{"automated":{"selfHeal":false}}}}'
          ## delete the htpass-secret
          oc delete secret htpass-secret -n openshift-config
          ## patch the oauth provider to have no idp
          oc patch oauth cluster --type=merge --patch '{"spec":{"identityProviders":null}}'
          ## Delete the tennant argocd apps
          for wapp in welcome-dev welcome-prod welcome-pipeline
          do
            oc patch application ${wapp} -n welcome-gitops  -p '{"metadata": {"finalizers": []}}' --type merge
            oc delete application ${wapp} -n welcome-gitops
          done
          ## Delete the cluster argocd applicationsets
          oc delete applicationsets cicd-demo -n openshift-gitops
          ## Delete the cluster argocd application
          for capp in tekton gitea argocd cluster-config
          do
            oc patch application ${capp} -n openshift-gitops  -p '{"metadata": {"finalizers": []}}' --type merge
            oc delete application ${capp} -n openshift-gitops
          done
          ## Delete argocd tennant instance
          oc delete argocd welcome-argocd -n welcome-gitops
          ## Delete namespaces. Don't wait for success
          for ns in scm welcome-dev welcome-gitops welcome-pipeline welcome-prod
          do
            oc delete ns ${ns} --wait=false
          done
          ## Delete subs
          for sub in $(oc get subs -n openshift-operators -o name | egrep 'gitops|pipelines|gitea')
          do
            oc delete ${sub} -n openshift-operators
          done
          ## Delete csv
          for csv in $(oc get csv -n openshift-operators -o name | egrep 'gitops|pipelines|gitea')
          do
            oc delete ${csv} -n openshift-operators
          done
          ## Delete operators
          for op in gitea-operator.openshift-operators openshift-gitops-operator.openshift-operators openshift-pipelines-operator-rh.openshift-operators
          do
            oc delete operator ${op}
          done
          ## Delete gitea catolog source
          oc delete $(oc get catalogsource -n openshift-marketplace -o name | grep gitea) -n openshift-marketplace
          ## Finally, delete the gitops project
          oc delete project openshift-gitops
          ## Exit 0 regaurdless of what actually happend
          exit 0
      imagePullPolicy: Always
  restartPolicy: Never
  serviceAccount: ocp-cicd-demo
  serviceAccountName: ocp-cicd-demo
